### ISSUE TITLE
Update Calendar Dies At 44 Characters

### ISSUE THREAD

**Issue by ibscas** [jamesiarmes/php-ews#300] opened 2015-11-04 15:42 UTC
This is somewhat in reference to the last issue I posted about mysterious "hangs" in the SOAP request.  When using your example at https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Update-Event everything works OK unless you change it.

For example, forgetting the start date update, if you try to set the subject to any more than 44 characters it hangs up.  So changing your code to:

```
$field->CalendarItem->Subject = 'New Subject ABCDEFGHIJKLMNOPQRSTUVWXYZ Test1';
```

It will hang up.

Is it possible there's a PHP setting I need to change that is limiting the buffer or something?  I can create new records with as long as a subject as a I need, but updating them dies.

**Comment by ibscas** [comment] 2015-11-05 18:57
I added a CURL timeout to the process, it reveals that no data was received, I'm not sure if this is helpful in determining the issue or not:  Curl error: Operation timed out after 19429 milliseconds with 0 out of 0 bytes received

**Comment by jamesiarmes** [comment] 2016-12-09 02:02
Marking this as a duplicate of #312.

**Closed by jamesiarmes** 2016-12-09 02:02 UTC
Labels: Duplicate
