### ISSUE TITLE
Master and additional non-default Calendars of one user

### ISSUE THREAD

**Issue by psYkoMichel** [jamesiarmes/php-ews#483] opened 2018-01-28 20:11 UTC
Hello,

Version (e.g. 1.0, dev-master):
PHP version: PHP Version 7.0.12
Microsoft Exchange version: 2013

Description of problem:
I have a MS Exchange calendar which have more than once calendar. One is the master or default calendar. 

How can i get a list with all calendars of the user?
How can i control on which calendar my new event will be written?

Thanks for your support and any kind of hints.

Michael

**Comment by jamesiarmes** [comment] 2018-03-02 18:38
This is a duplicate of #435.

To summarize, other calendars will be a subfolder of DistinguishedFolderIdNameType::CALENDAR. Once you have the folder id, you can specify that as the parent folder id.

**Closed by jamesiarmes** 2018-03-02 18:38 UTC
Labels: duplicate
