### ISSUE TITLE
Get all events of users in the same domain

### ISSUE THREAD

**Issue by Cracs22** [jamesiarmes/php-ews#416] opened 2017-02-27 16:14 UTC
Version (e.g. 1.0, dev-master):
PHP version: PHP 5.5

Description of problem:

I have two users in my Office365 with the same domain (myapp.onmicrosoft.com) like this :

User1 : user1@myapp.onmicrosoft.com
User2 : user2@myapp.onmicrosoft.com

For the moment I connect users one by one to get their contacts or calendar events but this is really restricted.
Is there a solution to get for exemple all calendar events of users in a special domain (myapp.onmicrosoft.com) ?
So, I could use this to get all events of category "tasks" for exemple.

Thanks

**Comment by talalong** [comment] 2017-02-27 20:45
this #408 could help you

**Comment by jamesiarmes** [comment] 2017-03-03 01:16
This appears to be a duplicate of #408.

**Closed by jamesiarmes** 2017-03-03 01:16 UTC
Labels: duplicate
