### ISSUE TITLE
Composer gives a problem message

### ISSUE THREAD

**Issue by caglaror** [jamesiarmes/php-ews#423] opened 2017-03-16 06:13 UTC
In composer.json i described your example require source.

> "php-ews/php-ews": "dev-master"

 But composer gives an error as below:

>   Problem 1
>     - Installation request for php-ews/php-ews dev-master -> satisfiable by php-ews/php-ews[dev-master].
>     - php-ews/php-ews dev-master requires jamesiarmes/php-ntlm ~1.0.0 -> satisfiable by jamesiarmes/php-ntlm[1.0.0-beta.1, 1.
> 0.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by jamesiarmes** [comment] 2017-03-16 16:21
This is a duplicate of #333.

**Closed by jamesiarmes** 2017-03-16 16:21 UTC
Labels: duplicate
